networks:
  nginx-challenge:
    driver: bridge

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nginx_challenge
    volumes:
      - ./db-data:/var/lib/mysql
      - ./db/migrations:/docker-entrypoint-initdb.d
    networks:
      - nginx-challenge
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 10s
      retries: 3

  app:
    container_name: app
    build:
      context: ./server
    depends_on:
      db:
        condition: service_healthy
    entrypoint: sh -c "npm install && npm run start"
    environment:
      PORT: 3000
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: nginx_challenge
    volumes:
      - ./server:/usr/src/app
    networks:
      - nginx-challenge

  nginx:
    image: nginx
    container_name: nginx
    build:
      context: ./nginx
    depends_on:
      - app
    restart: always
    tty: true
    ports:
      - '8080:80'
    networks:
      - nginx-challenge
