name: Generate README

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Generate README
      uses: crislainesc/template/.github/workflows/generate-readme@main
      with:
        repo_name: ${{ steps.repo-name.outputs.name }}
        formatted_name: ${{ steps.convert-name.outputs.formatted }}
